### ISSUE TITLE
error on local file IllegalFormatConversionException

### ISSUE THREAD

**Issue by dineshchavhan** [ConvertAPI/convertapi-java#17]
this is the full kotlin code

    @RequiresApi(Build.VERSION_CODES.Q)
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        when(requestCode){
            SELECT_REQUEST -> {
                val input = data!!.data
                val folder: File? = Environment.getExternalStoragePublicDirectory("${Environment.DIRECTORY_DOWNLOADS}/pptToPdf/")
                Config.setDefaultSecret("SECRET_CODE")
                ConvertApi.convert("pptx", "pdf",
                        Param("file", Paths.get(getFilePath(input!!)))
                ).get().saveFile(Paths.get(folder!!.path)).get()

            }
            else -> return
        }
    }

    @RequiresApi(Build.VERSION_CODES.Q)
    private fun getFilePath(uri: Uri):String{
        val path = uri.path
                val filename = path!!.substring(path.lastIndexOf("/") + 1)
        val file = File(externalCacheDir, filename)
        file.createNewFile()
        FileOutputStream(file).use { outputStream ->
            contentResolver.openInputStream(uri).use { inputStream ->
                if (inputStream != null) {
                    FileUtils.copy(inputStream, outputStream)
                }
                outputStream.flush()
            }
        }
        return file.path
    }

AND THE ERROR IS

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.chavhan.pdfconverterfromoffice, PID: 5828
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1002, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:Download/pptexamples.ppt flg=0x1 }} to activity {com.chavhan.pdfconverterfromoffice/com.chavhan.pdfconverterfromoffice.MainActivity}: java.util.concurrent.ExecutionException: java.util.IllegalFormatConversionException: f != java.lang.String
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.util.concurrent.ExecutionException: java.util.IllegalFormatConversionException: f != java.lang.String
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:361)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1923)
        at com.chavhan.pdfconverterfromoffice.MainActivity.onActivityResult(MainActivity.kt:120)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.util.IllegalFormatConversionException: f != java.lang.String
        at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
        at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2898)
        at java.util.Formatter$FormatSpecifier.print(Formatter.java:2845)
        at java.util.Formatter.format(Formatter.java:2524)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2870)
        at com.convertapi.client.Http.getRequestBuilder(Http.java:61)
        at com.convertapi.client.ConvertApi.lambda$convert$0(ConvertApi.java:73)
        at com.convertapi.client.-$$Lambda$ConvertApi$DHu1fqnXgXGPutW81zP_QKRvc6Y.get(Unknown Source:8)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1627)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1619)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by kmozsi** [comment]
@dineshchavhan, please upgrade to version 2.5, it should work now.
